[package]
name = "zero2prod"
version = "0.1.0"
authors = ["Sagi Sarussi <sagis@sagis.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.3.2"
